- hosts: all
  become: true
  roles:
    - geerlingguy.pip
    - geerlingguy.docker
  
  tasks:
    - name: Install PostgreSQL client
      apt:
        name: postgresql-client
        state: present
        update_cache: true

    - name: Создать директорию для сертификата PostgreSQL
      file:
        path: /root/.postgresql
        state: directory
        mode: '0700'
      tags:
        - download_cert

    - name: Скачать корневой сертификат PostgreSQL
      get_url:
        url: https://storage.yandexcloud.net/cloud-certs/CA.pem
        dest: /root/.postgresql/root.crt
        mode: '0644'
      tags:
        - download_cert

    - name: Create Redmine environment directory
      file:
        path: /opt/redmine
        state: directory
        mode: '0755'

    - name: Create Redmine environment file
      template:
        src: redmine.env.j2
        dest: "{{ redmine_env_file }}"
        mode: '0644'

    - name: Проверить подключение к базе данных
      command: >
        psql
        "host={{ db_host }}
        port={{ db_port }}
        sslmode={{ db_sslmode }}
        sslrootcert={{ db_sslrootcert }}
        dbname={{ db_name }}
        user={{ db_user }}
        target_session_attrs=read-write"
        -c "SELECT 1;"
      register: db_check
      changed_when: false
      failed_when: false

    - name: Run Redmine container
      community.docker.docker_container:
        name: "{{ redmine_container_name }}"
        image: "{{ redmine_image }}"
        state: started
        restart_policy: always
        env_file: "{{ redmine_env_file }}"
        ports:
          - "{{ redmine_port }}:3000"
      when: db_check.rc == 0
      register: container_start

    - name: Wait for Redmine to start
      uri:
        url: "http://localhost:{{ redmine_port }}/login"
        method: GET
        status_code: 200
      register: result
      until: result.status == 200
      retries: 30
      delay: 10
      when: container_start.changed

- hosts: webservers
  become: true
  vars_files:
    - group_vars/webservers/vault.yml

  tasks:
    - name: Create http_check config directory
      file:
        path: /etc/datadog-agent/conf.d/http_check.d
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Copy http_check configuration
      copy:
        dest: /etc/datadog-agent/conf.d/http_check.d/conf.yaml
        content: |
          init_config:

          instances:
            - name: redmine_health
              url: http://localhost:{{ redmine_port }}/login
              timeout: 1
              check_certificate_expiration: true
              skip_ssl_validation: true
      notify: Restart Datadog agent

    - name: Ensure Docker container dd-agent is running
      docker_container:
        name: dd-agent
        image: gcr.io/datadoghq/agent:7
        state: started
        restart_policy: unless-stopped
        env:
          DD_API_KEY: "{{ datadog_api_key }}"
          DD_SITE: "datadoghq.com"
          DD_DOGSTATSD_NON_LOCAL_TRAFFIC: "true"
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock:ro
          - /proc/:/host/proc/:ro
          - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
          - /var/lib/docker/containers:/var/lib/docker/containers:ro

  handlers:
    - name: Restart Datadog agent
      docker_container:
        name: dd-agent
        state: restarted
